/*
  Objective:
  Automatically insert a welcome message into a 'Messages' table
  whenever a new user is added to the 'Users' table.

  Use Case:
  Useful for default logging, onboarding flows, audit trails, etc.
*/


IF OBJECT_ID('Messages', 'U') IS NOT NULL DROP TABLE Messages;
IF OBJECT_ID('Users', 'U') IS NOT NULL DROP TABLE Users;
IF OBJECT_ID('trg_NewUserWelcome', 'TR') IS NOT NULL DROP TRIGGER trg_NewUserWelcome;
GO


CREATE TABLE Users (
    UserID INT PRIMARY KEY,
    UserName NVARCHAR(100),
    Email NVARCHAR(100)
);
GO


CREATE TABLE Messages (
    MsgID INT IDENTITY(1,1) PRIMARY KEY,
    UserID INT,
    MessageText NVARCHAR(255),
    SentAt DATETIME DEFAULT GETDATE()
);
GO


  --AFTER INSERT trigger
  --Purpose:
  --Automatically create a "Welcome" message when a new user signs up.

CREATE TRIGGER trg_NewUserWelcome
ON Users
AFTER INSERT
AS
BEGIN
    INSERT INTO Messages (UserID, MessageText)
    SELECT 
        UserID,
        'Welcome, ' + UserName + '! Thanks for joining us.'
    FROM INSERTED;
END;
GO


 --Test the trigger
INSERT INTO Users VALUES 
(101, 'Alice', 'alice@example.com'),
(102, 'Bob', 'bob@example.com');
GO

 --View messages generated by the trigger
SELECT * FROM Messages;




